name: Build Aseprite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      uses: mattnotmitt/install-apt-packages-action@v1
      with:
        packages: |
          libx11-dev
          libxcursor-dev
          libxi-dev
          libgl1-mesa-dev
          libfontconfig1-dev

    - name: Setup CMake
      uses: actions/setup-cmake@v3

    - name: Build Aseprite
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j$(nproc)

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: aseprite
        path: build/bin/aseprite
